version: '3'

tasks:
  dev:setup:
    desc: "Main setup hook (Runs on postCreate)"
    cmds:
      - task: dev:shell
      - task: dev:git

  dev:start:
    desc: "Startup hook (Runs on postStart)"
    cmd: git submodule update --init --recursive

  dev:shell:
    desc: "Apply clean shell configuration"
    cmds:
      - cp .devcontainer/.zshrc ~/.zshrc
      - direnv allow .

  dev:git:
    desc: "Rewrite Git URLs to use Token (Codespaces Only)"
    status:
      - '[ "$CODESPACES" != "true" ]'
    vars:
      AuthURL: "https://x-access-token:{{.GITHUB_TOKEN}}@github.com/"
    cmds:
      - for: 
          - "ssh://git@github.com/"
          - "git@github.com/"
          - "git@github.com:"
        cmd: git config --global --add url.{{.AuthURL}}.insteadOf {{.ITEM}}

  # Build tasks
  build:release:
    desc: "Build the project in release mode"
    cmd: cargo build --release

  # Test tasks
  test:watch:
    desc: "Watch and run tests on changes"
    cmd: cargo watch -x test

  # Run tasks  
  run:watch:
    desc: "Watch and run the server on changes"
    cmd: cargo watch -x run

  # Clean tasks
  clean:docker:
    desc: "Clean Docker build cache"
    cmd: docker builder prune -f
