name: 'Setup Docker Buildx'
description: 'Configure Docker Buildx for multi-arch builds'
inputs:
  registry:
    description: 'Container registry (e.g., ghcr.io)'
    required: true
  username:
    description: 'Registry username'
    required: true
  password:
    description: 'Registry password/token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
